### ISSUE TITLE
MVP TODO

### ISSUE THREAD

**Issue by trixiegoff** [cottonflop/gyst#1]
- [x] Read in spec files
- [x] Parse specs step by step
- [x] Define steps
- [x] Step definition using specs
- [x] Step definition using native code from within specs
- [ ] Console output of executing and completed tests
- [ ] Step definition using native code
